# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - 'none'

pr:
  autoCancel: false
  branches:
    include:
    - master 


pool:
  vmImage: 'ubuntu-latest'

variables:
  isMain: $[or(startswith(variables['System.PullRequest.TargetBranch'], 'refs/heads/master'), startswith(variables['System.PullRequest.TargetBranch'], 'master'))] 

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo $(isMain)


